### ISSUE TITLE
Create a Footer

### ISSUE THREAD

**Issue by HrushikeshSurkar** [HrushikeshSurkar/game-store#4]
1. Create a footer that aligns with the theme of the website.
2. The footer should be simple and include a © Copyright text.

**Comment by Rahul-2006** [comment]
Hi @HrushikeshSurkar 
Can i work on this ?

**Comment by HrushikeshSurkar** [comment]
Hi Rahul-2006,

Thank you for your interest in the project. I'd like to follow up on your
offer to collaborate. Could you share more about your experience and how
you envision working together?

Looking forward to your response.

Best,
HrushikeshSurkar

**Comment by Rahul-2006** [comment]
So I am a beginner
I have done like 3 4 pr's and I am good at HTML CSS JavaScript react. So I
have sent you a PR , kindly check it if you can I have added the footer and
css.
